package com.example.ui.localization

import androidx.compose.runtime.compositionLocalOf

open class AppStrings {
    // Navigation & App Structure
    var navHome: String = "Home"
    var navAiChat: String = "AI Chat"
    var navPdfs: String = "PDFs"
    var navQuiz: String = "Quiz"
    var navNotes: String = "Notes"
    var navSettings: String = "Settings"

    // Home / Dashboard Screen
    var welcomePrefix: String = "Welcome"
    var welcomeSubtitle: String = "Ready to conquer your study goals with AI today?"
    var focusTime: String = "Focus Time"
    var focusSubtitle: String = "Pomodoro Study Sessions"
    var quickActions: String = "Quick Actions"
    var aiChat: String = "AI Chat"
    var voiceAi: String = "Voice AI"
    var pdfAssistant: String = "PDF Assistant"
    var imageOcr: String = "Image OCR"
    var aiQuiz: String = "AI Quiz"
    var flashcards: String = "Flashcards"
    var notes: String = "Notes"
    var pomodoro: String = "Pomodoro"
    var recentNotes: String = "Recent Notes"
    var viewAll: String = "View All"
    var noNotesCreated: String = "No Notes Created"
    var noNotesSubtitle: String = "Create study notes or auto-generate from PDF & OCR."
    var recentQuizScores: String = "Recent Quiz Scores"
    var noQuizzesTaken: String = "No Quizzes Taken"
    var noQuizzesSubtitle: String = "Take an AI Quiz to test your knowledge."
    var recentPdfDocuments: String = "Recent PDF Documents"
    var noPdfsUploaded: String = "No PDFs Uploaded"
    var noPdfsSubtitle: String = "Upload a textbook chapter or lecture notes to extract text."
    var mins: String = "mins"

    // Settings Screen
    var settingsTitle: String = "Settings & Preferences ⚙️"
    var userProfile: String = "User Profile"
    var displayName: String = "Display Name"
    var logOut: String = "Log Out"
    var saveProfile: String = "Save Profile"
    var languageSectionTitle: String = "App Language"
    var languageSectionSubtitle: String = "Select your preferred language for the entire app UI."
    var currentLanguage: String = "Current Language"
    var selectGeminiModel: String = "Select Gemini Model"
    var geminiModelSubtitle: String = "Choose the AI model used for Chat, Notes, and Quizzes."
    var currentAiModel: String = "Active AI Model"
    var customModelName: String = "Custom Model Name"
    var appTheme: String = "App Theme"
    var themeSystem: String = "System"
    var themeLight: String = "Light"
    var themeDark: String = "Dark"
    var dataStorage: String = "Data & Storage"
    var dataStorageSubtitle: String = "Clear local session data and reset cached state."
    var clearDataButton: String = "Clear Chat & Reset Data"
    var resetDialogTitle: String = "Reset App Data?"
    var resetDialogMsg: String = "This will clear chat history and restore default settings."
    var confirmReset: String = "Confirm Reset"
    var cancel: String = "Cancel"

    // AI Chat Screen
    var chatHeader: String = "AI Study Assistant 🤖"
    var chatSubtitle: String = "Ask any academic or conceptual question"
    var newChat: String = "New Chat"
    var chatHistory: String = "Chat History"
    var inputPlaceholder: String = "Ask a question in any language..."
    var send: String = "Send"
    var emptyChatTitle: String = "Start a New Conversation"
    var emptyChatSubtitle: String = "Ask questions, get summaries, solve math problems, or brainstorm ideas."
    var copiedToClipboard: String = "Copied to clipboard"

    // PDF Assistant Screen
    var pdfScreenTitle: String = "PDF Study Assistant 📄"
    var pdfScreenSubtitle: String = "Extract text from PDF documents, ask questions, and create study materials."
    var uploadPdfBtn: String = "Select PDF File"
    var selectPdf: String = "Upload & Extract PDF"
    var extractedContent: String = "Extracted PDF Content"
    var summaryTab: String = "Summary"
    var qnaTab: String = "Q&A"
    var flashcardsTab: String = "Flashcards"
    var quizTab: String = "Quiz"
    var generateSummaryBtn: String = "Generate Summary"
    var generateFlashcardsBtn: String = "Generate Flashcards"
    var generateQuizBtn: String = "Generate Quiz"
    var askPdfPlaceholder: String = "Ask a question about this PDF..."
    var noPdfUploadedTitle: String = "No PDF Selected"
    var noPdfUploadedSubtitle: String = "Upload a PDF document to begin reading and asking questions."

    // Quiz Screen
    var quizScreenTitle: String = "AI Quiz Generator 🎯"
    var createQuiz: String = "Create Quiz"
    var quizHistory: String = "History"
    var subjectTopicLabel: String = "Subject & Topic"
    var generateQuizAction: String = "Generate AI Quiz"
    var submitQuiz: String = "Submit Quiz"
    var reviewAnswers: String = "Review Answers"
    var retakeQuiz: String = "Retake Quiz"
    var noQuizHistory: String = "No Quiz History"
    var createAiQuiz: String = "Create AI Quiz"
    var backToQuizzes: String = "Back to Quizzes"
    var exit: String = "Exit"
    var score: String = "Score"
    var quizOutstanding: String = "Outstanding! 🎉"
    var quizGoodEffort: String = "Good Effort! 📚"
    var quizKeepPracticing: String = "Keep Practicing! 💪"
    var newQuiz: String = "New Quiz"
    var submitQuizAnswers: String = "Submit Answers"
    var subjectTopicDesc: String = "Enter subject and topic for an accurate tailored quiz."
    var subjectOptional: String = "Subject (Optional)"
    var subjectPlaceholder: String = "e.g. Computer Science, Mathematics, Physics"
    var topicRequired: String = "Topic *"
    var topicPlaceholder: String = "e.g. Photosynthesis, Algebra, Digital Logic"
    var difficultyLevel: String = "Difficulty Level"
    var diffEasy: String = "Easy"
    var diffMedium: String = "Medium"
    var diffHard: String = "Hard"
    var questionCount: String = "Number of Questions"
    var questionsSuffix: String = "Questions"
    var quizInfoNote: String = "Generates multiple-choice, true/false, and fill-in-the-blank questions with detailed explanations."
    var generatingQuestions: String = "Generating questions"
    var createNewQuiz: String = "Create New AI Quiz"
    var tailoredTestSubtitle: String = "Tailored test for any subject or topic"
    var openQuizForm: String = "Open Quiz Form"
    var quizHistoryScores: String = "Quiz History & Scores"
    var completed: String = "Completed"
    var noQuizResultsYet: String = "No Quiz Results Yet"
    var noQuizResultsSub: String = "Tap 'Open Quiz Form' to take a test and track your score history."
    var questionNumber: String = "Question"
    var trueFalse: String = "True / False"
    var fillInBlank: String = "Fill in the Blank"
    var multipleChoice: String = "Multiple Choice"
    var typeAnswerPlaceholder: String = "Type your answer here"
    var correctAnswer: String = "Correct Answer"
    var deleteResult: String = "Delete Result"

    // Flashcards Screen
    var flashcardsScreenTitle: String = "Flashcards Decks 🗂️"
    var createDeck: String = "Create Deck"
    var deckNameLabel: String = "Deck Name"
    var topicLabel: String = "Topic / Content"
    var tapToFlip: String = "Tap to Flip"
    var next: String = "Next"
    var previous: String = "Previous"
    var noFlashcardsYet: String = "No flashcards found in this deck."
    var allDecks: String = "All Decks"
    var noFlashcardsFound: String = "No Flashcards Found"
    var noFlashcardsSubtitle: String = "Tap ✨ Generate with AI to instantly create a study deck from any topic."
    var generateAiFlashcards: String = "Generate AI Flashcards"
    var addManualFlashcard: String = "Add Manual Flashcard"
    var questionHeader: String = "QUESTION (TAP TO FLIP)"
    var answerHeader: String = "ANSWER"
    var deckNamePrompt: String = "Deck Name (e.g. Computer Science)"
    var topicOrContentPrompt: String = "Topic or Study Content"
    var numberOfFlashcards: String = "Number of Flashcards:"
    var generateCardsBtn: String = "Generate"
    var frontQuestion: String = "Front (Question)"
    var backAnswer: String = "Back (Answer)"
    var saveCard: String = "Save Card"
    var deleteDeckFolder: String = "Delete Deck"
    var deleteFlashcard: String = "Delete Card"

    // Notes Screen
    var notesScreenTitle: String = "Study Notes 📝"
    var newNote: String = "New Note"
    var searchNotesPlaceholder: String = "Search notes by title or content..."
    var noteTitleLabel: String = "Note Title"
    var noteContentLabel: String = "Note Content (Markdown supported)"
    var saveNote: String = "Save Note"
    var deleteNote: String = "Delete Note"
    var pinnedNotes: String = "Pinned Notes"
    var allNotes: String = "All Notes"
    var noNotesFound: String = "No Notes Found"
    var noNotesMatchingSearch: String = "No notes matching your search query."
    var generateAiNote: String = "Generate AI Note"
    var rawTextPrompt: String = "Paste raw text or lecture transcript..."
    var generateFormattedNote: String = "Generate Formatted Note"

    // Pomodoro Timer Screen
    var pomodoroScreenTitle: String = "Pomodoro Study Timer ⏱️"
    var pomodoroSubtitle: String = "Boost focus with interval studying and smart breaks"
    var workInterval: String = "Work Interval"
    var shortBreak: String = "Short Break"
    var longBreak: String = "Long Break"
    var startTimer: String = "Start Focus"
    var pauseTimer: String = "Pause"
    var resetTimer: String = "Reset"
    var sessionsCompleted: String = "Sessions Completed"
    var totalFocusTime: String = "Total Focus Time"
    var currentStreak: String = "Current Streak"
    var selectPreset: String = "Select Duration Preset"
    var sessionInProgress: String = "Session in Progress"
    var focusModeActive: String = "Focus Mode Active 🔥"
    var sessionPaused: String = "Session Paused ⏸️"
    var readyToFocus: String = "Ready to Focus 📚"
    var resume: String = "Resume"
    var saveAndLog: String = "Save & Log"
    var recentFocusHistory: String = "Recent Focus History"
    var focusSession: String = "Focus Session"

    // Voice & OCR Screens
    var voiceAssistantTitle: String = "Voice Study Assistant 🎙️"
    var tapToSpeak: String = "Tap microphone to speak..."
    var listening: String = "Listening..."
    var ocrScreenTitle: String = "Image OCR & Solver 📷"
    var uploadOrSnap: String = "Upload or Capture Image"
    var extractAndSolve: String = "Extract & Solve with AI"
    var ocrChangeImage: String = "Change Image"
    var ocrClear: String = "Clear"
    var ocrSelectImagePrompt: String = "Select Image with Math, Question or Diagram"
    var ocrPickImage: String = "Pick Image from Gallery / Camera"
    var ocrAskQuestionTitle: String = "Ask a Question or Request"
    var ocrAskQuestionPlaceholder: String = "Ask anything about this image (e.g. solve problem, explain diagram, extract text)..."
    var ocrAnalyzingImage: String = "Analyzing Image..."
    var ocrProcessWithAi: String = "Process Image with AI"
    var ocrAskFollowup: String = "Ask Follow-up / Solve"
    var ocrAnalyzingDetails: String = "Analyzing image, scanning formulas, and solving with AI..."
    var ocrProcessingError: String = "Processing Error"
    var ocrAiSolutionTitle: String = "AI Solution & Analysis"
    var ocrEnterNoteHeading: String = "Enter note heading"
    var ocrNoteHeadingLabel: String = "Note Heading"
    var ocrNoteHeadingPlaceholder: String = "e.g. Calculus Derivatives"
    var ocrNoteSavedToast: String = "Note saved to Notes"
    var ocrCopiedToast: String = "Copied text to clipboard"
    var ocrSaveNoteBtn: String = "Save Note"
    var ocrSavedBtn: String = "Saved"

    // Study Timetable
    var timetable: String = "Timetable"
    var timetableTitle: String = "Study Timetable 📅"
    var timetableSubtitle: String = "Plan, track, and complete your scheduled study tasks"
    var addTask: String = "Add Study Task"
    var editTask: String = "Edit Task"
    var taskTitle: String = "Task / Topic"
    var taskTitlePlaceholder: String = "e.g. Solve Integration problems, Read Chapter 4"
    var subjectLabel: String = "Subject / Category"
    var timetableSubjectPlaceholder: String = "e.g. Mathematics, Physics, History"
    var dateLabel: String = "Date (YYYY-MM-DD)"
    var timeLabel: String = "Time"
    var timePlaceholder: String = "e.g. 10:00 AM, 04:30 PM"
    var priorityLabel: String = "Priority Level"
    var priorityLow: String = "Low"
    var priorityMedium: String = "Medium"
    var priorityHigh: String = "High"
    var saveTask: String = "Save Task"
    var markCompleted: String = "Mark as Finished"
    var markIncomplete: String = "Mark Unfinished"
    var pending: String = "Pending"
    var overdue: String = "Overdue / Unfinished ⚠️"
    var noTasksTitle: String = "No Study Tasks Scheduled"
    var noTasksSubtitle: String = "Tap + to add your study schedule for today or upcoming days."
    var filterAll: String = "All"
    var filterToday: String = "Today"
    var filterUpcoming: String = "Upcoming"
    var filterCompleted: String = "Completed"
    var taskSavedToast: String = "Study task saved"
    var taskCompletedToast: String = "Task marked as completed! 🎉"
    var taskDeletedToast: String = "Task removed"
    var deleteTaskDialogTitle: String = "Delete Study Task?"
    var deleteTaskDialogMsg: String = "Are you sure you want to remove this scheduled task?"
    var delete: String = "Delete"
    var completionProgress: String = "Timetable Progress"
    var tasksCompleted: String = "tasks completed"
    var reminderNotificationTitle: String = "Study Reminder 📚"
    var reminderNotificationOverdue: String = "Unfinished study task reminder:"
    var reminderNotificationTime: String = "Time to study:"
    var enableNotificationsPrompt: String = "Enable reminders for your study timetable"
    var grantPermission: String = "Allow Notifications"
    var studyReminderSet: String = "Reminder enabled for task"
    var reminderNotificationSent: String = "Reminder notification sent"
    var sendTestReminder: String = "Test Reminder"

    // Dashboard & Cards extra
    var scoreLabel: String = "Score"
    var tapToOpenNote: String = "Tap to open note"

    // Common Actions
    var activeBadge: String = "Active"
    var search: String = "Search"
    var done: String = "Done"
    var close: String = "Close"
    var retry: String = "Retry"
}

inline fun appStrings(init: AppStrings.() -> Unit): AppStrings {
    return AppStrings().apply(init)
}

val LocalAppStrings = compositionLocalOf { AppStrings() }

object LocalizationHelper {
    fun getStrings(languageCode: String): AppStrings {
        val code = languageCode.lowercase().trim()
        return com.example.ui.localization.languages.LanguageRegistry.get(code)
    }
}
